// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"gorm.io/gorm"
	"learning-go-gin/config"
	"learning-go-gin/controllers"
	"learning-go-gin/router"
)

// Injectors from wire.go:

func initializeApp(conf config.Config, dbConn *gorm.DB, r *gin.Engine) App {
	userController := controllers.NewUserController()
	userRouter := router.NewUserRouter(userController)
	blogController := controllers.NewBlogController()
	blogRouter := router.NewBlogRouter(blogController)
	routerRouter := router.NewRouter(r, userRouter, blogRouter)
	app := NewApp(conf, routerRouter)
	return app
}

// wire.go:

var superSet = wire.NewSet(controllers.Set, router.Set, NewApp)
